// Isolated PostgreSQL checks for close, reversal, earned icons, and recurrence.
const {PGlite}=require('@electric-sql/pglite');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const root=path.resolve(__dirname,'..');
const read=name=>fs.readFileSync(path.join(root,'supabase/migrations',name),'utf8');
const migration=fs.readdirSync(path.join(root,'supabase/migrations'));
const file=suffix=>read(migration.find(name=>name.endsWith(suffix)));
(async()=>{
 const db=new PGlite();
 await db.exec(fs.readFileSync(path.join(__dirname,'fixtures/schema-before-design.sql'),'utf8'));
 await db.exec(file('_verified_admin_identity.sql'));
 const owner=randomUUID(),player=randomUUID(),other=randomUUID(),authId=randomUUID(),sessionId=randomUUID();
 for(const [id,name,admin] of [[owner,'Owner',true],[player,'Player',false],[other,'Other',false]])await db.query('insert into officebets.members(id,name,is_admin) values($1,$2,$3)',[id,name,admin]);
 await db.query('insert into auth.users values($1,$2,now(),null)',[authId,'owner@example.test']);
 await db.query('insert into auth.sessions values($1,$2)',[sessionId,authId]);
 await db.query('insert into officebets.admin_identities(member_id,auth_user_id) values($1,$2)',[owner,authId]);
 await db.exec(file('_verified_admin_actions.sql'));
 await db.query("insert into officebets.ledger(user_id,kind,amount,details,at) values($1,'TRANSFER_SENT',-1001,'Historical send',now()),($1,'BUY',-1,'Historical weekend bet','2026-09-26T12:00:00Z')",[other]);
 const legacy=(await db.query("insert into officebets.markets(creator,title,category,closes_at,names,reserves,vault,winner) values($1,'Legacy resolved','general',now()+interval '1 day',array['YES','NO'],array[200,200],0,0) returning id",[owner])).rows[0].id;
 await db.query("insert into officebets.ledger(user_id,kind,amount,details,market_id) values($1,'SETTLEMENT',10,'Historical payout',$2),(null,'HOUSE_RETURN',190,'Historical house return',$2)",[other,legacy]);
 await db.query('update officebets.members set balance=balance+10 where id=$1',[other]);
 await db.query('update officebets.house set returned=returned+190 where id=1');
 let sql=file('_closed_markets_achievements_recurrence.sql');
 sql=sql.replace('create extension if not exists pg_cron;','').replace(/select cron\.schedule\([^;]+;/,'');
 await db.exec(sql);
 await db.exec(file('_recurring_audit_indexes.sql'));
 assert.deepEqual((await db.query('select achievement from officebets.member_achievements where member_id=$1 order by achievement',[other])).rows.map(r=>r.achievement),['how_did_we_get_here','loan_shark']);
 const auth=async(valid=true)=>db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claims',$2,false)",[valid?authId:'',JSON.stringify(valid?{session_id:sessionId}:{})]);
 const query=async(sql,params=[])=> (await db.query(sql,params)).rows;
 const action=async(user,kind,args={},request=randomUUID())=>(await query('select public.ob_action($1,$2,$3,$4::jsonb) result',[request,user,kind,JSON.stringify(args)]))[0].result;
 const rejected=async(fn,pattern)=>{let error;try{await fn();}catch(e){error=e;}assert(error,'Expected rejection');if(pattern)assert.match(error.message,pattern);};
 await auth(false);
 assert.equal((await query('select count(*)::integer n from officebets.resolution_entry_links x join officebets.resolutions r on r.id=x.resolution_id where r.market_id=$1',[legacy]))[0].n,2);
 await rejected(()=>action(owner,'reverse_resolution',{market:legacy}),/Verified admin/);
 await rejected(()=>action(owner,'create_persistent',{title:'Forbidden'}),/Verified admin/);
 const market=(await action(player,'create_market',{title:'Close fixture',description:'',category:'general',closesAt:new Date(Date.now()+86400000).toISOString(),outcomes:['YES','NO']})).markets.find(m=>m.title==='Close fixture');
 await rejected(()=>action(other,'close_market',{market:market.id}),/Only creator/);
 await action(player,'close_market',{market:market.id});
 assert.equal((await query('select winner,closed_permanently from officebets.markets where id=$1',[market.id]))[0].closed_permanently,true);
 await rejected(()=>action(player,'buy',{market:market.id,outcome:0,amount:1,minOut:0}),/Trading is closed/);
 await rejected(()=>action(player,'close_market',{market:market.id}),/cannot be closed again/);
 await rejected(()=>action(other,'settle',{market:market.id,outcome:0}),/Only the creator/);
 await auth();
 await action(owner,'reverse_resolution',{market:legacy});
 assert.equal(Number((await query('select vault from officebets.markets where id=$1',[legacy]))[0].vault),200);
 assert.equal((await query("select count(*)::integer n from officebets.ledger where market_id=$1 and kind in ('SETTLEMENT','HOUSE_RETURN') and resolution_id is null",[legacy]))[0].n,2);
 await action(owner,'admin_user',{user:owner,name:'Owner',avatar:'⚡',bio:'',balance:2000});
 await action(owner,'transfer',{recipient:other,amount:1000.01,memo:'Qualifying send'});
 assert((await query('select achievement from officebets.member_achievements where member_id=$1',[owner])).some(a=>a.achievement==='loan_shark'));
 const snap=await action(owner,'admin_user',{user:player,name:'Player',avatar:'⚡',bio:'',balance:0});
 assert(snap.users.find(u=>u.id===player).achievements.includes('biggest_loser'));
 await rejected(()=>action(player,'profile',{name:'Player',avatar:'🦈',bio:''}),/locked/);
 await db.query('insert into officebets.positions(user_id,market_id,outcome,shares,cost) values($1,$2,0,100,5)',[player,market.id]);
 const before=(await query('select balance from officebets.members where id=$1',[player]))[0].balance;
 const houseBefore=(await query('select returned from officebets.house where id=1'))[0].returned;
 await action(owner,'settle',{market:market.id,outcome:0});
 assert((await query('select achievement from officebets.member_achievements where member_id=$1',[player])).some(a=>a.achievement==='master_better'));
 await action(player,'transfer',{recipient:other,amount:100,memo:'Move credited GW'});
 await action(owner,'reverse_resolution',{market:market.id});
 const after=(await query('select balance from officebets.members where id=$1',[player]))[0].balance;
 assert.equal(Number(after),Number(before)-100);
 assert.equal(Number((await query('select returned from officebets.house where id=1'))[0].returned),Number(houseBefore));
 assert.equal((await query('select winner,closed_permanently,vault from officebets.markets where id=$1',[market.id]))[0].closed_permanently,true);
 assert.equal((await query('select count(*)::integer n from officebets.ledger where reverses_ledger_id is not null'))[0].n,4);
 await rejected(()=>action(owner,'reverse_resolution',{market:market.id}),/not resolved/);
 await rejected(()=>action(owner,'buy',{market:market.id,outcome:0,amount:1,minOut:0}),/Trading is closed/);
 await action(owner,'admin_user',{user:player,name:'Player',avatar:'🎰',bio:''});
 const definition={title:'Daily target',description:'Rule',category:'general',outcomes:['YES','NO'],cadence:'daily',weekday:null,closeTime:'17:00:00+00'};
 await rejected(()=>action(player,'create_persistent',definition),/Verified admin/);
 const created=await action(owner,'create_persistent',definition);
 assert.equal(created.persistentBets.length,1);
 const d=created.persistentBets[0],slot=new Date(d.nextOpenAt);
 await query('select officebets.process_persistent_bets($1)',[new Date(slot.getTime()+60000).toISOString()]);
 await query('select officebets.process_persistent_bets($1)',[new Date(slot.getTime()+60000).toISOString()]);
 assert.equal((await query('select count(*)::integer n from officebets.markets where persistent_bet_id=$1',[d.id]))[0].n,1);
 await query('select officebets.process_persistent_bets($1)',[new Date(slot.getTime()+86400000+60000).toISOString()]);
 assert.equal((await query('select count(*)::integer n from officebets.markets where persistent_bet_id=$1',[d.id]))[0].n,2);
 await query('select officebets.process_persistent_bets($1)',[new Date(slot.getTime()+3*86400000+60000).toISOString()]);
 assert.equal((await query('select count(*)::integer n from officebets.markets where persistent_bet_id=$1',[d.id]))[0].n,3);
 await action(owner,'edit_persistent',{...definition,definition:d.id,title:'Changed future'});
 assert.equal((await query('select title from officebets.markets where persistent_bet_id=$1 order by opens_at limit 1',[d.id]))[0].title,'Daily target');
 const weekly={...definition,title:'Weekly',cadence:'weekly',weekday:(new Date().getUTCDay()+2)%7,closeTime:'18:00:00+00'};
 const weeklyCreated=await action(owner,'create_persistent',weekly),weeklyId=weeklyCreated.persistentBets.find(x=>x.title==='Weekly').id;
 const weeklySlot=new Date(weeklyCreated.persistentBets.find(x=>x.id===weeklyId).nextOpenAt);
 await query('select officebets.process_persistent_bets($1)',[new Date(weeklySlot.getTime()+60000).toISOString()]);
 const weeklyClose=new Date((await query('select closes_at from officebets.markets where persistent_bet_id=$1',[weeklyId]))[0].closes_at);
 await query('select officebets.process_persistent_bets($1)',[new Date(weeklyClose.getTime()+86400000+60000).toISOString()]);
 await query('select officebets.process_persistent_bets($1)',[new Date(weeklyClose.getTime()+86400000+60000).toISOString()]);
 assert.equal((await query('select count(*)::integer n from officebets.markets where persistent_bet_id=$1',[weeklyId]))[0].n,2);
 await action(owner,'create_persistent',{...definition,title:'Third'});
 await rejected(()=>action(owner,'create_persistent',{...definition,title:'Fourth'}),/Only three/);
 await action(owner,'delete_persistent',{definition:d.id});
 assert.equal((await query('select count(*)::integer n from officebets.persistent_bets where active'))[0].n,2);
 assert.equal((await query('select count(*)::integer n from officebets.markets where persistent_bet_id=$1',[d.id]))[0].n,3);
 await db.close();console.log('Feature SQL checks passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
