// Mocked UI checks; no live Supabase writes.
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const admin='11111111-1111-4111-8111-111111111111',player='22222222-2222-4222-8222-222222222222';
const user=(id,isAdmin)=>({id,name:isAdmin?'Organizer':'Player',isAdmin,active:true,avatar:'⚡',bio:'',balance:1000,balanceExact:'1000',slips:[],achievements:[],lastSuperchargedAt:null});
const market=(i,resolved=false)=>({id:`33333333-3333-4333-8333-${String(i).padStart(12,'0')}`,title:`Prediction ${i}`,description:'A rule',creatorId:player,categoryId:'general',createdAt:new Date(Date.now()-i*60000).toISOString(),closesAt:new Date(Date.now()+86400000).toISOString(),resolved,winningOutcomeIdx:resolved?0:null,closedPermanently:resolved,everTraded:i!==1,volume:100-i,collateralVault:200,outcomes:[{name:'YES',poolReserve:200},{name:'NO',poolReserve:200}]});
const snapshot={revision:1,serverTime:new Date().toISOString(),users:[user(admin,true),user(player,false)],markets:[market(1),market(2),market(3),market(4,true)],persistentBets:[{id:'55555555-5555-4555-8555-555555555555',title:'Daily prediction',description:'Rule',categoryId:'general',outcomes:['YES','NO'],cadence:'daily',closeTime:'17:00:00+00',weekday:null,active:true,nextOpenAt:new Date(Date.now()+86400000).toISOString()}],categories:[{id:'general',name:'General'}],transactions:[],house:{granted:0,returned:0}};
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],requests=[];let authority=admin;
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.route('**/*',route=>{const url=route.request().url();if(url==='https://officebets.test/')return route.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(root,'index.html'),'utf8')});if(url.includes('/rpc/ob_snapshot'))return route.fulfill({json:snapshot});if(url.includes('/rpc/ob_admin_status'))return route.fulfill({json:{memberId:authority}});if(url.includes('/rpc/ob_market_view'))return route.fulfill({json:{history:[],activity:[]}});if(url.includes('/rpc/ob_action')){requests.push(route.request().postDataJSON());return route.fulfill({json:{...snapshot,revision:++snapshot.revision}});}if(url.includes('/auth/v1/logout')){authority=null;return route.fulfill({status:204});}return route.abort();});
 await page.routeWebSocket('**/*',ws=>ws.close());await page.goto('https://officebets.test/');await page.waitForFunction(()=>state.markets.length===4);
 await page.evaluate(id=>switchTeammate(id),player);
 assert(await page.locator('.market-overflow-trigger').count()>0);
 await page.locator('.prediction-card .market-overflow-trigger').first().click();
 assert(await page.getByRole('menuitem',{name:'Close prediction early'}).count());
 assert.equal(await page.getByRole('menuitem',{name:'Resolve early'}).count(),0);
 assert.equal(await page.getByRole('menuitem',{name:'Delete prediction'}).count(),0);
 await page.getByRole('menuitem',{name:'Close prediction early'}).click();
 assert.equal(requests.at(-1).p_action,'close_market');
 await page.waitForFunction(()=>!pendingAction()&&!busy);
 await page.evaluate(()=>openProfile());
 const locked=page.locator('#avatarChoices button.locked');assert.equal(await locked.count(),4);
 assert.equal(await locked.first().getAttribute('title'),'Loan Shark');assert(await locked.first().isDisabled());
 await page.evaluate(()=>hideUtility('profileModal'));
 await page.evaluate(id=>{switchTeammate(id);verifiedAdminId=id;renderAll();},admin);
 await page.locator('.prediction-card .market-overflow-trigger').first().click();
 assert(await page.getByRole('menuitem',{name:'Resolve early'}).count());
 assert(await page.getByRole('menuitem',{name:'Delete prediction'}).count());
 await page.evaluate(()=>closeMarketMenu());
 await page.evaluate(()=>openMarketMenu({stopPropagation(){},currentTarget:document.querySelectorAll('.prediction-card .market-overflow-trigger')[3]},state.markets[3].id));
 assert(await page.getByRole('menuitem',{name:'Reverse resolution'}).count());
 await page.getByRole('menuitem',{name:'Reverse resolution'}).click();assert.equal(requests.at(-1).p_action,'reverse_resolution');
 assert(await page.locator('#persistentBets').getByText('Daily prediction').count());
 assert(await page.locator('#persistentCreate').isVisible());
 await page.locator('#persistentCreate').click();assert(await page.locator('#persistentModal').isVisible());
 await page.locator('#persistentQuestion').fill('New recurring prediction');await page.locator('#persistentModal button[type=submit]').click();
 assert.equal(requests.at(-1).p_action,'create_persistent');
 await page.waitForFunction(()=>!pendingAction()&&!busy);
 const cta=await page.locator('#sidebarNewPrediction').evaluate(el=>{const s=getComputedStyle(el);return {color:s.color,border:s.borderColor,background:s.backgroundImage}});
 assert.equal(cta.color,'rgb(255, 255, 255)');assert.match(cta.background,/gradient/);
 assert(await page.locator('#featuredPrev').isDisabled());await page.locator('#featuredNext').click();assert.equal(await page.locator('#featuredPrev').isDisabled(),false);
 snapshot.users[0].achievements=['loan_shark'];await page.evaluate(()=>{applySnapshot({...state,revision:state.revision+1,serverTime:new Date().toISOString(),users:state.users.map(u=>u.id===localActiveUserId?{...u,achievements:['loan_shark']}:u)});openProfile();});
 assert.equal(await page.locator('#avatarChoices button.locked').count(),3);
 await page.evaluate(()=>hideUtility('profileModal'));await page.screenshot({path:path.join(process.env.TEMP||root,'officebets-feature-desktop.png'),fullPage:true});
 await page.evaluate(()=>{const now=Math.floor(Date.now()/1000),sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';const token=btoa(JSON.stringify({alg:'HS256',typ:'JWT'}))+'.'+btoa(JSON.stringify({sub,role:'authenticated',session_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',exp:now+3600}))+'.signature';sessionStorage.setItem('sb-yennoorczvfaygjmoubt-auth-token',JSON.stringify({access_token:token,refresh_token:'test-refresh',token_type:'bearer',expires_at:now+3600,expires_in:3600,user:{id:sub,aud:'authenticated',role:'authenticated',email:'admin@example.test',app_metadata:{},user_metadata:{}}}));});
 await page.reload();await page.waitForFunction(()=>state.markets.length===4&&canAdmin());
 authority=null;await page.evaluate(()=>refreshAdminAuthority());assert.equal(await page.evaluate(()=>canAdmin()),false);
 authority=admin;await page.evaluate(()=>refreshAdminAuthority());assert.equal(await page.evaluate(()=>canAdmin()),true);
 await page.evaluate(()=>signOutAdmin());await page.waitForFunction(()=>!canAdmin());
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{hideUtility('profileModal');renderAll();});
 assert.equal(await page.locator('#sidebarNewPrediction').isVisible(),true);
 assert.equal(await page.locator('#persistentBets').isVisible(),true);
 await page.screenshot({path:path.join(process.env.TEMP||root,'officebets-feature-mobile.png'),fullPage:true});
 assert.deepEqual(errors,[]);await browser.close();console.log('Feature UI checks passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
