// High-value interaction tests. No network writes; Auth/RPC responses are deterministic doubles.
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),adminId='11111111-1111-4111-8111-111111111111',userId='22222222-2222-4222-8222-222222222222';
const user=(id,name,isAdmin)=>({id,name,isAdmin,active:true,avatar:'⚡',bio:'On the grid',balance:1000,balanceExact:'1000',slips:[],lastSuperchargedAt:null});
const titles=['Will we have labeling by end of week?','Goldfish get restocked by friday','Office bets survives the week','Will Monday’s Teamwide Sync be rescheduled','Who will say “Can everyone hear me?” next?','Daily: Members of the team start laughing uncontrollably'];
const markets=Array.from({length:10},(_,i)=>({id:`33333333-3333-4333-8333-${String(i).padStart(12,'0')}`,title:titles[i%6],description:'Trading details stay here.',creatorId:userId,categoryId:i<5?'general':'meetings',createdAt:new Date(Date.now()-86400000).toISOString(),closesAt:new Date(Date.now()+(i+1)*3600000).toISOString(),resolved:i===9,winningOutcomeIdx:i===9?0:null,everTraded:i!==1,volume:1000-i*10,collateralVault:200,outcomes:i===4?[{name:'Josh',poolReserve:200},{name:'Eric',poolReserve:240},{name:'Max',poolReserve:400},{name:'Other',poolReserve:500}]:[{name:'YES',poolReserve:300},{name:'NO',poolReserve:200}]}));
let snapshot={revision:1,serverTime:new Date().toISOString(),users:[user(adminId,'Colton',true),user(userId,'Max',false)],markets,categories:[{id:'general',name:'General'},{id:'meetings',name:'Meetings'}],transactions:[],house:{granted:0,returned:0}},authority=null,history=[],requests=[];
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>{const url=route.request().url();if(url==='https://officebets.test/')return route.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(root,'index.html'),'utf8')});if(url.includes('/rpc/ob_snapshot'))return route.fulfill({json:snapshot});if(url.includes('/rpc/ob_admin_status'))return route.fulfill({json:{memberId:authority}});if(url.includes('/rpc/ob_market_view'))return route.fulfill({json:{history,activity:[]}});if(url.includes('/rpc/ob_action')){const r=route.request().postDataJSON();requests.push(r);return route.fulfill({json:{...snapshot,revision:++snapshot.revision}});}if(url.includes('/auth/v1/logout')){authority=null;return route.fulfill({status:204});}return route.abort();});await page.routeWebSocket('**/*',ws=>ws.close());
 await page.clock.install();await page.goto('https://officebets.test/');await page.waitForFunction(()=>state.markets.length===10);
 assert.equal(await page.locator('#heroProfileButton').count(),0);assert.equal(await page.locator('#featuredTimeline polyline').count(),1);assert.match(await page.locator('#featuredTimeline').innerText(),/Current odds/);
 assert.doesNotMatch(await page.locator('#view-markets').innerText(),/volume|collateral|View prediction|Trading details/);
 assert.equal(await page.locator('.prediction-card .market-overflow-trigger').count(),0);
 // Badge ID alone never exposes admin controls.
 await page.evaluate(id=>switchTeammate(id),adminId);assert.equal(await page.locator('.prediction-card .market-overflow-trigger').count(),0);await page.click('#settingsButton');assert.equal(await page.getByRole('button',{name:'Admin sign-in',exact:true}).count(),1);await page.evaluate(()=>hideUtility('settingsModal'));
 // Carousel automatic progression and pause/play.
 await page.mouse.move(0,0);await page.evaluate(()=>{featuredPaused=false;featuredElapsed=0;updateFeaturedPlayback();});const original=await page.evaluate(()=>featuredMarketId);await page.clock.runFor(8250);assert.notEqual(await page.evaluate(()=>featuredMarketId),original);
 await page.click('#featuredPause');assert.equal(await page.evaluate(()=>featuredPaused),true);const paused=await page.evaluate(()=>featuredMarketId);await page.mouse.move(0,0);await page.clock.runFor(9000);assert.equal(await page.evaluate(()=>featuredMarketId),paused);
 await page.click('#featuredPause');assert.equal(await page.evaluate(()=>featuredPaused),false);await page.mouse.move(0,0);await page.clock.runFor(8250);assert.notEqual(await page.evaluate(()=>featuredMarketId),paused);
 await page.click('#featuredNext');assert.equal(await page.evaluate(()=>featuredPaused),true);assert.equal(await page.locator('#tradeModal').isVisible(),false);
 await page.locator('#featuredMarket article').focus();assert.equal(await page.evaluate(()=>featuredPaused),true);
 // Singleton history uses a line, never an invented trend.
 history=[{at:new Date().toISOString(),odds:[.28,.72],kind:'TRADE'}];await page.evaluate(()=>{featuredHistory.clear();featuredRequests.clear();renderFeatured();});await page.waitForFunction(()=>document.getElementById('featuredTimeline').textContent.includes('One recorded quote'));
 const points=await page.locator('#featuredTimeline polyline').getAttribute('points');const ends=points.split(' ').map(p=>p.split(',').map(Number));assert(ends[1][0]>ends[0][0]);assert.equal(ends[0][1],ends[1][1]);
 // Row edges reflect limits, large click region and scroll preservation.
 const row=page.locator('.category-row').first(),shell=page.locator('.carousel-shell').first();assert.equal(await shell.locator('.prev').isDisabled(),true);assert.equal(await shell.locator('.next').isDisabled(),false);const edge=await shell.locator('.next').boundingBox(),card=await row.locator('.prediction-card').first().boundingBox();assert(edge.height>card.height*.9);
 await row.evaluate(r=>r.scrollTo({left:r.scrollWidth,behavior:"instant"}));await page.waitForFunction(()=>document.querySelector(".carousel-shell .next").disabled);assert.equal(await shell.locator('.next').isDisabled(),true);assert.equal(await shell.locator('.prev').isDisabled(),false);const scroll=await row.evaluate(r=>r.scrollLeft);await page.evaluate(()=>renderMarketsGrid());assert.equal(await row.evaluate(r=>r.scrollLeft),scroll);await row.evaluate(r=>r.scrollTo({left:0,behavior:"instant"}));
 // Verified authority reveals overflow; menu is outside the clipped shelf.
 authority=adminId;await page.evaluate(()=>refreshAdminAuthority());const first=page.locator('.prediction-card').first();await first.locator('.market-overflow-trigger').click();assert.equal(await page.locator('#marketOverflow').isVisible(),true);assert.equal(await page.locator('#tradeModal').isVisible(),false);await page.keyboard.press('Escape');assert.equal(await page.locator('#marketOverflow').isVisible(),false);assert.equal(await first.locator('.market-overflow-trigger').evaluate(e=>e===document.activeElement),true);
 const editable=page.locator('.prediction-card').nth(1);await editable.locator('.market-overflow-trigger').click();await page.getByRole('menuitem',{name:'Edit prediction',exact:true}).click();assert.equal(await page.locator('#newMarketModal').isVisible(),true);assert.equal(await page.locator('#newMarketTitleInput').inputValue(),markets[1].title);await page.fill('#newMarketTitleInput','Admin revision');await page.locator('#newMarketModal button[type=submit]').click();assert(requests.some(r=>r.p_action==='edit_market'&&r.p_args.title==='Admin revision'));
 // Destructive action cancellation does not send an RPC; confirmed path does.
 await first.locator('.market-overflow-trigger').click();page.once('dialog',d=>d.dismiss());await page.getByRole('menuitem',{name:'Delete prediction',exact:true}).click();assert.equal(requests.filter(r=>r.p_action==='delete_market').length,0);
 await first.locator('.market-overflow-trigger').click();page.once('dialog',d=>d.accept());await page.getByRole('menuitem',{name:'Delete prediction',exact:true}).click();await page.waitForFunction(()=>!busy);assert.equal(requests.filter(r=>r.p_action==='delete_market').length,1);
 // Viewing another profile and editing existing fields; separate role confirmation.
 await first.locator('.creator-link').click();assert.equal(await page.locator('#profileViewModal').isVisible(),true);await page.locator('#profileViewModal').getByRole('button',{name:'Edit profile',exact:true}).click();await page.fill('#adminAvatar','🦊');await page.fill('#adminBio','Forecast captain');await page.locator('#adminUserModal button[type=submit]').click();await page.waitForFunction(()=>!busy);assert(requests.some(r=>r.p_action==='admin_user'&&r.p_args.avatar==='🦊'&&r.p_args.bio==='Forecast captain'));await page.evaluate(id=>openAdminUser(id),userId);await page.fill('#adminRoleEmail','max@example.test');page.once('dialog',d=>d.dismiss());await page.click('#adminRoleButton');assert.equal(requests.filter(r=>r.p_action==='admin_role').length,0);page.once('dialog',d=>d.accept());await page.click('#adminRoleButton');await page.waitForFunction(()=>!busy);assert(requests.some(r=>r.p_action==='admin_role'&&r.p_args.grant===true&&r.p_args.confirmName==='Max'));await page.evaluate(()=>hideUtility('settingsModal'));
 // Core trade, profile, transfer and boost handlers retain their RPC contracts.
 await first.locator('.market-title-button').click();await page.fill('#tradeAmountInput','10');await page.evaluate(()=>recalculateTradePreview());await page.evaluate(()=>executeCurrentTrade());assert(requests.some(r=>r.p_action==='buy'&&r.p_args.amount==='10'&&r.p_args.minOut>0));
 await page.evaluate(()=>claimDailySupercharge());assert(requests.some(r=>r.p_action==='boost'));
 await page.evaluate(()=>openTransferModal());await page.selectOption('#transferRecipientSelect',userId);await page.fill('#transferAmountInput','5');await page.fill('#transferMemoInput','Great forecast');await page.locator('#transferModal button[type=submit]').click();await page.waitForFunction(()=>!busy);assert(requests.some(r=>r.p_action==='transfer'&&r.p_args.amount==='5'));
 // Snapshot of real typography, long questions, categorical cards and admin overflow.
 await page.evaluate(()=>{document.getElementById('appNotice').textContent='';renderAll();});if(process.env.SCREENSHOT_DIR)await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,'approved-design-desktop.png'),fullPage:true});
 for(const width of [1440,1024,760,390]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow at ${width}`);assert.equal(await page.locator('#superchargeBtn').isVisible(),true);assert.equal(await page.locator('#accountMenu').isVisible(),true);assert.equal(await page.locator('#featuredTimeline').isVisible(),true);await page.locator('.market-title-button').first().click();assert.equal(await page.locator('#tradeModal').isVisible(),true);assert(await page.locator('.prediction-dialog').evaluate(e=>e.getBoundingClientRect().width<=innerWidth));await page.evaluate(()=>closeTradeModal());if(width===390&&process.env.SCREENSHOT_DIR)await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,'approved-design-mobile.png'),fullPage:true});}
 await page.emulateMedia({reducedMotion:'reduce'});await page.clock.runFor(100);assert.equal(await page.evaluate(()=>featuredPaused),true);
 // Logout locks authority; selected creators retain permitted controls on cards and in detail.
 await page.evaluate(()=>badgeOut());await page.evaluate(id=>switchTeammate(id),userId);assert(await page.locator('.prediction-card .market-overflow-trigger').count()>0);await page.locator('.prediction-card').first().locator('.market-title-button').click();assert.equal(await page.locator('#predictionTools .market-overflow-trigger').count(),1);await page.evaluate(()=>closeTradeModal());
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: approved density, autoplay/pause/manual/focus/reduced-motion, timeline fallback, edge limits, scroll preservation, admin menus/confirmation/profile/roles, trading/transfer/boost and desktop/narrow layouts');
})().catch(e=>{console.error(e);process.exit(1)});
